# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2a672a0da0b11b1c42388d3ee4eb861455ccbae8639b725b0adeb8e6724dc4f29313af1636b6de7654bb2e97732bfe7b252832233e38b9a606cde27f0a4df01

test:
  secret_key_base: d49ed6b929c0da56fd7023df6e5997cd2e72808870cb0c8fec7d86185a105145b0bd45d7dc6638af8c94105421618a64b7e554903e74d40931ad459961184c5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
